#!/usr/bin/bash

if [[ ${SHELL} == *"/bash"* ]]; then
    SRC=${BASH_SOURCE}
else
    SRC=$0
fi

BIN_DIR=$(dirname $(readlink -e ${SRC}))
BASEDIR=${BIN_DIR%/*}

export PATH=${PATH}:${BASEDIR}/bin
export GENGINE=${BASEDIR}

if [[ ${SHELL} == *"/bash"* ]]; then
    export PS1="[gengine]${PS1}"
else
    export PROMPT="[gengine]${PROMPT}"
fi

echo "[gengine] Enabled with ${GENGINE}"
